application: pubhub-za
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /pay_stripe
  script: main.app
  secure: always
- url: /api/stripe_payment
  script: main.app
  secure: always

# - url: /api/.*
#   script: main.app
#   secure: always

- url: /admin
  script: main.app
  login: admin
- url: /admin/.*
  script: main.app
  login: admin

- url: /static
  static_dir: static
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: PIL
  version: latest
